-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLGameViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:12:10 +0000



-- Objective C interface: @interface AAPLGameViewController
local AAPLGameViewController = objc.classInterface ("AAPLGameViewController") --[[ @inherits UIViewController, @protocols SCNSceneRendererDelegate]]

function AAPLGameViewController:isHighEndDevice ()  --[[@return bool]] end
function AAPLGameViewController:addTrainToScene_atPosition (scene --[[@type objc.SCNScene]], pos --[[@type struct.SCNVector3]])  --[[@return nil]] end