-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLGameViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-09-30 08:53:45 +0000



-- Objective C interface: @interface AAPLGameViewController
local AAPLGameViewController = objc.classInterface ("AAPLGameViewController") --[[ @inherits UIViewController, @protocols SCNSceneRendererDelegate]]

AAPLGameViewController.loadingImageCenterConstraint --[[@type objc.NSLayoutConstraint]] = nil
function AAPLGameViewController:isHighEndDevice ()  --[[@return bool]] end
function AAPLGameViewController:addTrainToScene_atPosition (scene --[[@type objc.SCNScene]], pos --[[@type struct.SCNVector3]])  --[[@return nil]] end
function AAPLGameViewController:loadingImageCenterConstraint ()  --[[@return objc.NSLayoutConstraint]] end
function AAPLGameViewController:setLoadingImageCenterConstraint (loadingImageCenterConstraint --[[@type objc.NSLayoutConstraint]])  --[[@return nil]] end