-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLGameView.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:12:11 +0000



-- Objective C interface: @interface AAPLGameView
local AAPLGameView = objc.classInterface ("AAPLGameView") --[[ @inherits SCNView]]

AAPLGameView.touchCount --[[@type integer]] = 0
AAPLGameView.inCarView --[[@type bool]] = false
function AAPLGameView:touchCount ()  --[[@return integer]] end
function AAPLGameView:setTouchCount (touchCount --[[@type integer]])  --[[@return nil]] end
function AAPLGameView:inCarView ()  --[[@return bool]] end
function AAPLGameView:setInCarView (inCarView --[[@type bool]])  --[[@return nil]] end