-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLOverlayScene.h
-- Generated by Celedev® LuaBindingsGenerator on 2015-05-20 16:12:12 +0000



-- Objective C interface: @interface AAPLOverlayScene
local AAPLOverlayScene = objc.classInterface ("AAPLOverlayScene") --[[ @inherits SKScene]]

AAPLOverlayScene.speedNeedle --[[@type objc.SKNode]] = nil
function AAPLOverlayScene:speedNeedle ()  --[[@return objc.SKNode]] end