-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AppDelegate.h
-- Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:17 +0000



-- Objective C interface: @interface AppDelegate
local AppDelegate = objc.classInterface ("AppDelegate") --[[ @inherits UIResponder, @protocols UIApplicationDelegate]]

AppDelegate.window --[[@type objc.UIWindow]] = property()
function AppDelegate:window () --[[@return objc.UIWindow]] end
function AppDelegate:setWindow (window --[[@type objc.UIWindow]]) --[[@return nil]] end

