-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/GameViewController.h
-- Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:18 +0000



-- Objective C interface: @interface GameViewController
local GameViewController = objc.classInterface ("GameViewController") --[[ @inherits UIViewController, @protocols SCNSceneRendererDelegate]]

GameViewController.loadingImageCenterConstraint --[[@type objc.NSLayoutConstraint]] = property { kind = 'weak' }
GameViewController.yAcceleration --[[@type number]] = property()
function GameViewController:isHighEndDevice () --[[@return bool]] end
function GameViewController:loadingImageCenterConstraint () --[[@return objc.NSLayoutConstraint]] end
function GameViewController:setLoadingImageCenterConstraint (loadingImageCenterConstraint --[[@type objc.NSLayoutConstraint]]) --[[@return nil]] end
function GameViewController:yAcceleration () --[[@return number]] end
function GameViewController:setYAcceleration (yAcceleration --[[@type number]]) --[[@return nil]] end

