-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/GameView.h
-- Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:17 +0000



-- Objective C interface: @interface GameView
local GameView = objc.classInterface ("GameView") --[[ @inherits SCNView]]

GameView.touchCount --[[@type integer]] = property()
GameView.inCarView --[[@type bool]] = property()
function GameView:touchCount () --[[@return integer]] end
function GameView:setTouchCount (touchCount --[[@type integer]]) --[[@return nil]] end
function GameView:inCarView () --[[@return bool]] end
function GameView:setInCarView (inCarView --[[@type bool]]) --[[@return nil]] end

