-- Lua bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/OverlayScene.h
-- Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:18 +0000



-- Objective C interface: @interface OverlayScene
local OverlayScene = objc.classInterface ("OverlayScene") --[[ @inherits SKScene]]

OverlayScene.speedNeedle --[[@type objc.SKNode]] = property { kind = 'readonly' }
function OverlayScene:speedNeedle () --[[@return objc.SKNode]] end

