// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLGameViewController.h
// Generated by Celedev® LuaBindingsGenerator on 2015-09-30 08:53:45 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "AAPLGameViewController.h"

// Register Objective C methods extended signatures

@implementation AAPLGameViewController (LuaModule_SceneKitVehicle_AAPLGameViewController)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(addTrainToScene:atPosition:), "v36@0:8@\"SCNScene\"16{SCNVector3=fff}24" },
        { @selector(loadingImageCenterConstraint), "z@\"NSLayoutConstraint\"16@0:8" },
        { @selector(setLoadingImageCenterConstraint:), "v24@0:8z@\"NSLayoutConstraint\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:3 forClass:[AAPLGameViewController class]];
}

@end

