// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLOverlayScene.h
// Generated by Celedev® LuaBindingsGenerator on 2015-09-30 08:53:47 +0000
// Target Architecture: armv7

#import "CIMLua/CIMLuaBindings.h"

#import "AAPLOverlayScene.h"

// Register Objective C methods extended signatures

@implementation AAPLOverlayScene (LuaModule_SceneKitVehicle_AAPLOverlayScene)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(speedNeedle), "@\"SKNode\"8@0:4" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:1 forClass:[AAPLOverlayScene class]];
}

@end

