// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLOverlayScene.h
// Generated by Celedev® LuaBindingsGenerator on 2015-09-16 10:12:08 +0000
// Target Architecture: arm64

#import "CIMLua/CIMLuaBindings.h"

#import "AAPLOverlayScene.h"

// Register Objective C methods extended signatures

@implementation AAPLOverlayScene (LuaModule_SceneKitVehicle_AAPLOverlayScene)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(speedNeedle), "@\"SKNode\"16@0:8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:1 forClass:[AAPLOverlayScene class]];
}

@end

