// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AAPLGameView.h
// Generated by Celedev® LuaBindingsGenerator on 2015-09-16 10:12:07 +0000
// Target Architecture: armv7

#import "CIMLua/CIMLuaBindings.h"

#import "AAPLGameView.h"

// Register Objective C methods extended signatures

@implementation AAPLGameView (LuaModule_SceneKitVehicle_AAPLGameView)

+ (void) load
{

    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(inCarView), "c\"BOOL\"8@0:4" },
        { @selector(setInCarView:), "v12@0:4c\"BOOL\"8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:2 forClass:[AAPLGameView class]];
}

@end

