// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/AppDelegate.h
// Target Architecture: arm64
// Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:18 +0000

#import "CIMLua/CIMLuaBindings.h"

#import "AppDelegate.h"

// Register Objective C methods extended signatures

@implementation AppDelegate (LuaModule_SceneKitVehicle_AppDelegate)

+ (void) load
{
    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(window), "@\"UIWindow\"16@0:8" },
        { @selector(setWindow:), "v24@0:8@\"UIWindow\"16" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:2 forClass:[AppDelegate class]];
}

@end

