// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/GameView.h
// Target Architecture: armv7
// Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:17 +0000

#import "CIMLua/CIMLuaBindings.h"

#import "GameView.h"

// Register Objective C methods extended signatures

@implementation GameView (LuaModule_SceneKitVehicle_GameView)

+ (void) load
{
    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(inCarView), "c\"BOOL\"8@0:4" },
        { @selector(setInCarView:), "v12@0:4c\"BOOL\"8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:2 forClass:[GameView class]];
}

@end

