// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/GameViewController.h
// Target Architecture: armv7
// Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:18 +0000

#import "CIMLua/CIMLuaBindings.h"

#import "GameViewController.h"

// Register Objective C methods extended signatures

@implementation GameViewController (LuaModule_SceneKitVehicle_GameViewController)

+ (void) load
{
    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(isHighEndDevice), "c\"BOOL\"8@0:4" },
        { @selector(loadingImageCenterConstraint), "@\"NSLayoutConstraint\"8@0:4" },
        { @selector(setLoadingImageCenterConstraint:), "v12@0:4@\"NSLayoutConstraint\"8" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:3 forClass:[GameViewController class]];
}

@end

