// Lua to C bindings for /Volumes/Brume/Celedev CodeFlow/CodeFlow Sample Applications/SceneKitVehicle/SceneKitVehicle/OverlayScene.h
// Target Architecture: armv7
// Generated by Celedev® LuaBindingsGenerator on 2016-10-10 15:27:18 +0000

#import "CIMLua/CIMLuaBindings.h"

#import "OverlayScene.h"

// Register Objective C methods extended signatures

@implementation OverlayScene (LuaModule_SceneKitVehicle_OverlayScene)

+ (void) load
{
    CIMLuaObjcMethodAttributes instanceMethodsAttributes [] = {
        { @selector(speedNeedle), "@\"SKNode\"8@0:4" }
    };
    [CIMLuaContext registerObjcInstanceMethodsAttributes:instanceMethodsAttributes withCount:1 forClass:[OverlayScene class]];
}

@end

